# Interactive component

## Data
This interactive graph shows overall and potential ratings of players in different nations. We choose Top 10 nations and players whose overall rating is greater than 75. The radius of the circle represents the number of players, so a circle with larger radius means more players with the same overall and potential rating.

## Interactive graph
<script src="https://d3js.org/d3.v6.js"></script>

<style>
body {
  margin: 0;
  font-family: arial, sans;
}

.label {
  font-size: 15px;
}

.legend{
  opacity: 1;
  transition: opacity 0.3s;
}

.legend text,
.axis text {
  font-size: 13px;
  fill: #333;
}

.axis path,
.axis line {
  fill: none;
  stroke-width:1px;
  stroke: #e7e7e7;
}

circle {
  stroke: #fff;
}

.bubble {
  opacity: 1;
  transition: opacity 0.3s;
}

.bubble text {
  opacity: 0;
  pointer-events: none;
  font-size: 15px;
}

.bubble:hover text {
  opacity: 1;
}

.bubble:hover circle {
  fill-opacity: 1;
}

</style>

<div id="plot"></div>

<script>
var margin = { top: 30, right: 85, bottom: 40, left: 50 };
var width = 780 - margin.left - margin.right;
var height = 450 - margin.top - margin.bottom;

var svg = d3.select("div#plot")
  .append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

var xscale = d3.scaleLinear()
  .domain([75, 98])
  .range([0,width]);

var yscale = d3.scaleLinear()
  .domain([75, 98])
  .range([height,0]);

var radius = d3.scaleSqrt()
  .range([1,16]);

var xAxis = d3.axisBottom()
  .tickSize(-height)
  .scale(xscale);

var yAxis = d3.axisLeft()
  .tickSize(-width)
  .scale(yscale)

var color = d3.scaleOrdinal(d3.schemeCategory10);

d3.csv("https://raw.githubusercontent.com/JackJing001/fifa21data/main/FIFArating.csv").then(function(data) {
  console.log(data);
  // data pre-processing
  data.forEach(function(d) {
    d.y = +d["Potential"];
    d.x = +d["Overall"];
    d.r = +d["Freq"];
  });

  radius.domain(d3.extent(data, function(d) {
    return d.r;
  })).nice();

  svg.append("g")
    .attr("transform", "translate(0," + height + ")")
    .attr("class", "x axis")
    .call(xAxis);

  svg.append("g")
    .attr("transform", "translate(0,0)")
    .attr("class", "y axis")
    .call(yAxis);

  var group = svg.selectAll("g.bubble")
    .data(data)
    .enter().append("g")
    .attr("class", "bubble")
    .attr("transform", function(d) {
      return "translate(" + xscale(d.x) + "," + yscale(d.y) + ")"
    });

  group
    .append("circle")
    .attr("r", function(d) { return radius(d.r);  })
    .style("fill", function(d) {
      return color(d["Nationality"]);
    });
    
  group
    .append("text")
    .attr("x", function(d) { return radius(d.r); })
    .attr("alignment-baseline", "middle")
    .text(function(d) {
      return d["Overall"]+"/"+d["Potential"];  
    });

  svg.append("text")
    .attr("x", 6)
    .attr("y", -2)
    .attr("class", "label")
    .text("Potential");

  svg.append("text")
    .attr("x", width-2)
    .attr("y", height-6)
    .attr("text-anchor", "end")
    .attr("class", "label")
    .text("Oveall");

  var legend = svg.selectAll(".legend")
    .data(color.domain())
    .enter().append("g")
    .attr("class", "legend")
    .attr("transform", function(d, i) { return "translate(2," + i * 14 + ")"; });

  legend.append("rect")
      .attr("x", width)
      .attr("width", 12)
      .attr("height", 12)
      .style("fill", color);

  legend.append("text")
      .attr("x", width + 16)
      .attr("y", 6)
      .attr("dy", ".35em")
      .style("text-anchor", "start")
      .text(function(d) { return d; });

  legend.on("click", function() {
      d3.selectAll(".legend")
        .style("opacity", 0.1);
      d3.select(this)
        .style("opacity", 1);
      var nation = d3.select(this).select('text').text();
      d3.selectAll("circle")
        .style("opacity", 0)
        .filter(function(d) { return d["Nationality"] == nation; })
        .style("opacity", 1);
    });
    
  group.on("click", function() {
      d3.selectAll(".legend")
        .style("opacity", 1);
      d3.selectAll("circle")
        .style("opacity", 1);
    });
    
});



</script>

## How to interactive
Because many players have the same overall and potential ratings, the static graph is hard to show the different rating distributions in different nations. You can click the rectangular label on the right to check players' ratings in different nations. Then move your mouse over the circle to check the exact "Overall rating/Potential rating".

If you want to reset the graph, just click a circle that you like :)

## Results

1. Brazil and Spain have the most good players whose overall ratings are greater than 75.
2. However, if we only consider players whose overall ratings are greater than 85, then Brazil, France and Germany own the most excellent players.
3. Only 4 players' overall ratings are greater than 90, they come from Argentina, Belgium, Brazil and Portugal. All of them are the most famous super stars in football world. Although I don't put their names in the graph, I believe if you know some football, you know they are Messi, De Bruyne, Neymar and C. Ronaldo.
4. England, Italy, Portugal are the most potential nations. Although they don't have so many players whose overall ratings are greater than 85, they own a lot of players whose potential ratings are greater than 85.
5. Spain owns a lot of good players whose overall ratings are greater than 75, but most of them are not potential or excellent enough.

## Who is gonna win the World Cup!
According to the data in FIFA21, we guess Brazil, France and Germany are the
strongest competitors for the World Cup Championship in 2022. But in 2026, England, Italy and Portugal will join their competitions.
