# Conclusion

From data analysis and data visualization we have done, we have a basic understanding about the players and the clubs in FIFA Football game. 

We first have some findings with respect to the age, rating, potential and wage. The players whose age are between 30 years old and 40 years old have the highest average ratings. The difference between potential and overall rating for young players follows a normal distribution with mean 15. Their ratings are potentially to increase by 15 in the future. For older players, their overall rating and potential are the same. The wage always has a positive relationship to the rating of a player. However, for young players, they are typically underpaid.

With regards to the game, we work on the players' styles and performance. We find out that there is no evidence to show that left-foot players are more talented than the right-foot players. We also discover a strong negative relationship between players CAM rating and CDM rating.For strength and speed, most players are both medium in Strength and Speed. By comparing the overall rating of each famous club, we believe the top 3 clubs in the game are FC Bayern München, Juventus and FC Barcelona.

From the interactive graph, we try to predict the best national team. We believe that  Brazil, France and Germany are the strongest competitors for the World Cup Championship in 2022. England, Italy, Portugal are the most potential nations.

Our data analysis and visualization have some limitations. Since there are almost 20,000 players and 95 variables in our FIFA data set, we did not fully represent the whole data set and could only choose some important aspects to visualize and analyze. There should be more information that could be digged out. Moreover, in some graphs, we could not represent all the players and we chose to filter the data in order to make the graph more intuitive. We hope that we could analyze more variables and have more findings to make the data set more meaningful and make the football fans have a direct understanding of FIFA21.

