--- 
title: "EDAV Final Project"
author: "Siwen Xie, Yifan Jing, Yuao Zhao"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

## Overview

This chapter introduces our topic and questions that we are interested in studying.

## Topic

FIFA is a series of football simulation video games developed and released annually by Electronic Arts under the EA Sports label. Listed in Guinness World Records as the best-selling sports video game franchise in the world, by 2021, the FIFA series had sold over 325 million copies. It is also one of the best-selling video game franchises.

Career mode is one of the most important game mode in FIFA. In career mode, there are over 10,000 real world players. According to their real information and appearance, FIFA sets an overall rating for each player. Besides that, each player also has ratings about their football skills like crossing, finishing, ball control and so on. These ratings are the most interesting parts in the game, and that's the reason why we choose to study the player dataset in FIFA.

We choose FIFA21, which is the latest version, as our dataset. Let's see what we can discover from this amazing game!

## Questions

In the player dataset in FIFA21, some data are the real data like a player's age, nationality; some data are ratings that are given based on their appearance in real world. So first, we can start from analyzing some real data to see the players preferred foot or the distribution of their wages. 

Then we can try to find some relationships between their ratings of different skills like if there is a relationship between a player's ability in short passing and long passing. Or if a striker's overall rating more related to his finishing ability or dribbling ability.

There are also some more interesting questions. Based on players' overall ratings, which national team is the best in the game? Based on their potential overall ratings, which club will be the best in the future?

We are gonna try to find answers to these interesting questions in our project.




